name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug GitHub OIDC
        uses: actions/github-script@v8
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com')
            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            )

            console.log('event_name:', payload.event_name)
            console.log('repository:', payload.repository)
            console.log('sub:', payload.sub)
            console.log('aud:', payload.aud)
            console.log('environment:', payload.environment)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::984285320293:role/enterprise-dev-github-actions-role
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color